# Generated by Django 5.2.6 on 2025-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_brand_category_offer_overview_overviewitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
