# Generated by Django 5.2.6 on 2025-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_aboutpage_color_product_description_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='inquiry_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='query_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='subtitle',
            field=models.CharField(default='For Online Orders', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='timing',
            field=models.CharField(default='10 AM - 7 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
    ]
