# Generated by Django 5.2.6 on 2025-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_footercontactinfo_remove_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='subitem',
            unique_together={('subcategory', 'slug')},
        ),
    ]
